const departsColom = {
  33: "Bogotá D.C.",
  1: "Amazonas",
  2: "Antioquia",
  3: "Arauca",
  4: "Atlántico",
  5: "Bolívar",
  6: "Boyacá",
  7: "Caldas",
  8: "Caquetá",
  9: "Casanare",
  10: "Cauca",
  11: "Cesar",
  12: "Chocó",
  13: "Córdoba",
  14: "Cundinamarca",
  15: "Guainía",
  16: "Guaviare",
  17: "Huila",
  18: "La Guajira",
  19: "Magdalena",
  20: "Meta",
  21: "Nariño",
  22: "Norte de Santander",
  23: "Putumayo",
  24: "Quindío",
  25: "Risaralda",
  26: "San Andrés y Providencia",
  27: "Santander",
  28: "Sucre",
  29: "Tolima",
  30: "Valle del Cauca",
  31: "Vaupés",
  32: "Vichada",
};

const typeNidSelect = {
  1: "Cédula de Ciudadanía",
  2: "Cédula de Extranjera",
  3: "Pasaporte",
};

const requiredGeneralMessage = "Campo Requerido"

const confirmPassword = (value, watch, watchOptions) => value === watch(watchOptions.toCompare) || "Las contraseñas no coinciden"

export const registerOptions = {
  usernameOptions: {
    name: "username",
    type: "text",
    label: "Usuario",
    placeholder: "user123",
    required: requiredGeneralMessage,
    minLength: 3,
    maxLength: 51,
    pattern: "",
  },
  nameOptions: {
    name: "name",
    type: "text",
    label: "Nombre",
    placeholder: "John",
    required: requiredGeneralMessage,
    minLength: 3,
    maxLength: 51,
    pattern: "",
  },
  surnameOptions: {
    name: "surname",
    type: "text",
    label: "Apellidos",
    placeholder: "Doe",
    required: requiredGeneralMessage,
    minLength: 3,
    maxLength: 51,
    pattern: "",
  },
  

  passwordOptions: {
    name: "password",
    type: "password",
    label: "Contraseña",
    placeholder: "",
    required: requiredGeneralMessage,
    minLength: 3,
    maxLength: 51,
    pattern: "",
  },
  password2Options: {
    name: "password2",
    type: "password",
    label: "Confirmar Contraseña",
    placeholder: "",
    required: requiredGeneralMessage,
    minLength: 3,
    maxLength: 51,
    pattern: "",
    validate: confirmPassword,
    watchOptions: {
      toCompare: "password"
    }
  },

  typeNidOptions: {
    name: "typeNID",
    type: "text",
    select: true,
    label: "Tipo de identificación",
    placeholder: "",
    required: requiredGeneralMessage,
    minLength: 1,
    maxLength: 51,
    pattern: "",
    options: typeNidSelect,
  },
  nidOptions: {
    name: "nid",
    type: "text",
    label: "Número de identificación",
    placeholder: "",
    required: requiredGeneralMessage,
    minLength: 3,
    maxLength: 51,
    pattern: "",
  },
  departmentOptions: {
    name: "department",
    type: "text",
    select: true,
    label: "Departamento",
    placeholder: "",
    required: requiredGeneralMessage,
    minLength: 1,
    maxLength: 51,
    pattern: "",
    options: departsColom,
  },
  cityOptions: {
    name: "city",
    type: "text",
    label: "Ciudad",
    placeholder: "",
    required: requiredGeneralMessage,
    minLength: 3,
    maxLength: 51,
    pattern: "",
  },
  addressOptions: {
    name: "addresss",
    type: "text",
    label: "Dirección",
    placeholder: "",
    required: requiredGeneralMessage,
    minLength: 3,
    maxLength: 51,
    pattern: "",
  },
};
